base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 3306
  username: root
  password: kenrome001

development:
  <<: *base
  database: ffedu

test:
  <<: *base
  database: ffedu

production:
  <<: *base
  database: ffedu
############################
remote: &remote
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: kenrome001
  host: 127.0.0.1
  port: 3303
#for exporter
common_development:
  <<: *remote
  database: ffedu

local_development:
  <<: *base
  database: forager